/*
 * These are the hardcoded modules
 */
DO_BUILTIN (sys)
DO_BUILTIN (_posix)
DO_BUILTIN (traceback)
DO_BUILTIN (_time)
DO_BUILTIN (_thread)
DO_BUILTIN (warnings)
DO_BUILTIN (_math)
DO_BUILTIN (binascii)
DO_BUILTIN (_itertools)
DO_BUILTIN (_JIT)
DO_BUILTIN (marshal)
DO_BUILTIN (struct)
DO_BUILTIN (gc)
DO_BUILTIN (_re)
DO_BUILTIN (_bisect)
DO_BUILTIN (errno)
DO_BUILTIN (builtins)
DO_BUILTIN (string)
DO_BUILTIN (_socket)
DO_BUILTIN (cStringIO)
DO_BUILTIN (_zlibfuncs)
DO_BUILTIN (_zlib)
DO_BUILTIN (_unicode)
DO_BUILTIN (html00)
